name: Actiontime

on:
  push:
    branches: ["master"]

jobs: 
  push_to_registry:
    name: Push Docker Image To Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker install
        uses: papodaca/install-docker-action@main
      - name: check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        runs:
          using: 'docker'
          image: 'Dockerfile'
